// libs/ng/lib5/src/lib/lib5-component8/lib5-component8.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib5-component8',
          templateUrl: './lib5-component8.component.html',
          styleUrls: ['./lib5-component8.component.css']
        })
        export class Lib5Component8Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib5/src/lib/lib5-component8.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib5-component8.css';
        
        export const Lib5Component8 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib5Component8;
