// libs/react/lib2/src/lib/lib2-component22.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib2-component22.css';
        
        export const Lib2Component22 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib2Component22;

// libs/ng/lib2/src/lib/lib2-component22/lib2-component22.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib2-component22',
          templateUrl: './lib2-component22.component.html',
          styleUrls: ['./lib2-component22.component.css']
        })
        export class Lib2Component22Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }
