// libs/ng/lib12/src/lib/lib12-component16/lib12-component16.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib12-component16',
          templateUrl: './lib12-component16.component.html',
          styleUrls: ['./lib12-component16.component.css']
        })
        export class Lib12Component16Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib12/src/lib/lib12-component16.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib12-component16.css';
        
        export const Lib12Component16 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib12Component16;
