// libs/ng/lib3/src/lib/lib3-component3/lib3-component3.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib3-component3',
          templateUrl: './lib3-component3.component.html',
          styleUrls: ['./lib3-component3.component.css']
        })
        export class Lib3Component3Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib3/src/lib/lib3-component3.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib3-component3.css';
        
        export const Lib3Component3 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib3Component3;
