// libs/react/lib14/src/lib/lib14-component7.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib14-component7.css';
        
        export const Lib14Component7 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib14Component7;

// libs/ng/lib14/src/lib/lib14-component7/lib14-component7.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib14-component7',
          templateUrl: './lib14-component7.component.html',
          styleUrls: ['./lib14-component7.component.css']
        })
        export class Lib14Component7Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }
