// libs/react/lib5/src/lib/lib5-component19.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib5-component19.css';
        
        export const Lib5Component19 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib5Component19;

// libs/ng/lib5/src/lib/lib5-component19/lib5-component19.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib5-component19',
          templateUrl: './lib5-component19.component.html',
          styleUrls: ['./lib5-component19.component.css']
        })
        export class Lib5Component19Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }
