// libs/ng/lib0/src/lib/lib0-component24/lib0-component24.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib0-component24',
          templateUrl: './lib0-component24.component.html',
          styleUrls: ['./lib0-component24.component.css']
        })
        export class Lib0Component24Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib0/src/lib/lib0-component24.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib0-component24.css';
        
        export const Lib0Component24 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib0Component24;
