// libs/ng/lib8/src/lib/lib8-component7/lib8-component7.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib8-component7',
          templateUrl: './lib8-component7.component.html',
          styleUrls: ['./lib8-component7.component.css']
        })
        export class Lib8Component7Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib8/src/lib/lib8-component7.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib8-component7.css';
        
        export const Lib8Component7 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib8Component7;
