// libs/ng/lib2/src/lib/lib2-component10/lib2-component10.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib2-component10',
          templateUrl: './lib2-component10.component.html',
          styleUrls: ['./lib2-component10.component.css']
        })
        export class Lib2Component10Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib2/src/lib/lib2-component10.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib2-component10.css';
        
        export const Lib2Component10 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib2Component10;
