// libs/ng/lib1/src/lib/lib1-component26/lib1-component26.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib1-component26',
          templateUrl: './lib1-component26.component.html',
          styleUrls: ['./lib1-component26.component.css']
        })
        export class Lib1Component26Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib1/src/lib/lib1-component26.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib1-component26.css';
        
        export const Lib1Component26 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib1Component26;
