// libs/react/lib6/src/lib/lib6-component2.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib6-component2.css';
        
        export const Lib6Component2 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib6Component2;

// libs/ng/lib6/src/lib/lib6-component2/lib6-component2.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib6-component2',
          templateUrl: './lib6-component2.component.html',
          styleUrls: ['./lib6-component2.component.css']
        })
        export class Lib6Component2Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }
