// libs/react/lib8/src/lib/lib8-component25.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib8-component25.css';
        
        export const Lib8Component25 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib8Component25;

// libs/ng/lib8/src/lib/lib8-component25/lib8-component25.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib8-component25',
          templateUrl: './lib8-component25.component.html',
          styleUrls: ['./lib8-component25.component.css']
        })
        export class Lib8Component25Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }
