// libs/ng/lib7/src/lib/lib7-component29/lib7-component29.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib7-component29',
          templateUrl: './lib7-component29.component.html',
          styleUrls: ['./lib7-component29.component.css']
        })
        export class Lib7Component29Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib7/src/lib/lib7-component29.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib7-component29.css';
        
        export const Lib7Component29 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib7Component29;
