// libs/ng/lib4/src/lib/lib4-component21/lib4-component21.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib4-component21',
          templateUrl: './lib4-component21.component.html',
          styleUrls: ['./lib4-component21.component.css']
        })
        export class Lib4Component21Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }

// libs/react/lib4/src/lib/lib4-component21.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib4-component21.css';
        
        export const Lib4Component21 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib4Component21;
