// libs/react/lib9/src/lib/lib9-component21.tsx

        import React from 'react';
        import { SHARED_CONST } from '@happyorg/shared-utils'; 

        import './lib9-component21.css';
        
        export const Lib9Component21 = () => {
          return (
            <div>
              <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
            </div>
          );
        };
        
        export default Lib9Component21;

// libs/ng/lib9/src/lib/lib9-component21/lib9-component21.component.ts

        import { Component, OnInit } from '@angular/core';
        import { SHARED_CONST } from '@happyorg/shared-utils';

        @Component({
          selector: 'happyorg-lib9-component21',
          templateUrl: './lib9-component21.component.html',
          styleUrls: ['./lib9-component21.component.css']
        })
        export class Lib9Component21Component implements OnInit {
          sharedConst = SHARED_CONST;
        
          constructor() { }
        
          ngOnInit() {
          }
        
        }
