// apps/ng-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'happyorg-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ng-app';
}


    <div>
      <happyorg-lib0-main></happyorg-lib0-main>
<happyorg-lib1-main></happyorg-lib1-main>
<happyorg-lib2-main></happyorg-lib2-main>
<happyorg-lib3-main></happyorg-lib3-main>
<happyorg-lib4-main></happyorg-lib4-main>
<happyorg-lib5-main></happyorg-lib5-main>
<happyorg-lib6-main></happyorg-lib6-main>
<happyorg-lib7-main></happyorg-lib7-main>
<happyorg-lib8-main></happyorg-lib8-main>
<happyorg-lib9-main></happyorg-lib9-main>
<happyorg-lib10-main></happyorg-lib10-main>
<happyorg-lib11-main></happyorg-lib11-main>
<happyorg-lib12-main></happyorg-lib12-main>
<happyorg-lib13-main></happyorg-lib13-main>
<happyorg-lib14-main></happyorg-lib14-main>
    </div>

// apps/react-app/src/app/app.tsx
import React from 'react';
import { ReactLib0 } from '@happyorg/react/lib0';
import { ReactLib1 } from '@happyorg/react/lib1';
import { ReactLib2 } from '@happyorg/react/lib2';
import { ReactLib3 } from '@happyorg/react/lib3';
import { ReactLib4 } from '@happyorg/react/lib4';
import { ReactLib5 } from '@happyorg/react/lib5';
import { ReactLib6 } from '@happyorg/react/lib6';
import { ReactLib7 } from '@happyorg/react/lib7';
import { ReactLib8 } from '@happyorg/react/lib8';
import { ReactLib9 } from '@happyorg/react/lib9';
import { ReactLib10 } from '@happyorg/react/lib10';
import { ReactLib11 } from '@happyorg/react/lib11';
import { ReactLib12 } from '@happyorg/react/lib12';
import { ReactLib13 } from '@happyorg/react/lib13';
import { ReactLib14 } from '@happyorg/react/lib14';

export const App = () => {
  return (
    <div>
      <ReactLib0></ReactLib0>
      <ReactLib1></ReactLib1>
      <ReactLib2></ReactLib2>
      <ReactLib3></ReactLib3>
      <ReactLib4></ReactLib4>
      <ReactLib5></ReactLib5>
      <ReactLib6></ReactLib6>
      <ReactLib7></ReactLib7>
      <ReactLib8></ReactLib8>
      <ReactLib9></ReactLib9>
      <ReactLib10></ReactLib10>
      <ReactLib11></ReactLib11>
      <ReactLib12></ReactLib12>
      <ReactLib13></ReactLib13>
      <ReactLib14></ReactLib14>
    </div>
  );
};

export default App;
